### ISSUE TITLE
Support formats with `Seek` bound

### ISSUE THREAD

**Issue by luizirber** [luizirber/niffler#17]
Some formats require `Read + Seek`, like [`bgzip`](https://docs.rs/bgzip/0.0.3/bgzip/read/struct.BGzReader.html). How to support it (and should we support it?)

Comment on Reddit about `Seek`: https://www.reddit.com/r/rust/comments/g69a5c/niffler_simple_and_transparent_support_for/fo9wtd0/

**Comment by natir** [comment]
I think a simple solution should create `get_reader_seek` and `get_writer_seek` these functions accepts `Box<dyn Read + Seek + 'a>`, `Box<dyn Write + Seek + 'a>` and return same type.

I didn't like this very much but after some small search and test it seems the best solution.
