### ISSUE TITLE
Another name

### ISSUE THREAD

**Issue by luizirber** [luizirber/niffler#2]
[ocf][0] is already taken on crates.io, and it was not a good name anyway (Open Compressed File). Suggestions?

[0]: https://crates.io/crates/ocf

**Comment by luizirber** [comment]
Since it sniffs the parameters to decide the proper reader, I thought about `sniffer` or some variation.

And for something that also sniffs... Maybe `niffler`?
https://harrypotter.fandom.com/wiki/Niffler

Both are `sniffer` and `niffler` are available on crates.io.

What do you think @natir?

**Comment by natir** [comment]
I have another idea like "juste read it" reduce in `jri` but your idea is better. I like niffler a lot!!

**Comment by luizirber** [comment]
renamed =]
