### ISSUE TITLE
Replace GzDecoder with MultiGzDecoder?

### ISSUE THREAD

**Issue by luizirber** [luizirber/niffler#27]
Should we replace the `GzDecoder` from flate2 with `MultiGzDecoder` (which would also support [BGZF](https://docs.rs/flate2/1.0.16/flate2/bufread/struct.MultiGzDecoder.html))?

Are there other consequences to use `MultiGzDecoder` with regular `gzip` files? (apparently not, it didn't brake any of our tests)

from https://github.com/onecodex/needletail/pull/45#issuecomment-651235214

Also connected to #24, since `niffler` users might want to use specific backends instead of our default choices.

**Comment by hcdenbakker** [comment]
Wow, I was just going to suggest this (I am trying out nibbler for some bioinformatics applications), and ran into this issue while testing it. Please do!

**Comment by luizirber** [comment]
> Wow, I was just going to suggest this (I am trying out nibbler for some bioinformatics applications), and ran into this issue while testing it. Please do!

Hah, cool! Do you want to test the `multigz` branch from #28 and see if it works for you? Or, given that you have more experience with BGZF, do you see any drawbacks of using `MultiGzDecoder` by default?

**Comment by hcdenbakker** [comment]
I do not see any or experienced any drawbacks of using `MultiGzDecoder` by default. I haven't done any serious bench marking, but if you work with Illumina data fresh from the machine `MultiGzDecoder` is your only option. I will test the `multigz` branch and will let you know what I find.

**Comment by hcdenbakker** [comment]
The `multigz` branch works great for me.

**Comment by luizirber** [comment]
2.1.1 released with this change, thanks for trying it @hcdenbakker!
