### ISSUE TITLE
CI and release process improvements

### ISSUE THREAD

**Issue by luizirber** [luizirber/niffler#30]
- Add GitHub templates for issues and PRs ([examples](https://github.com/datrs/hypercore/tree/master/.github))
- Add a CI check to see if the CHANGELOG was updated
- maybe setup some sort of autobump for the version?
- add a `publish` workflow that send new crate version to crates.io ([example from sourmash](https://github.com/dib-lab/sourmash/blob/master/.github/workflows/rust_publish.yml))

**Comment by Ebedthan** [comment]
Hi @luizirber,
* Concerning adding a template for issues, we can right away go with the template offered by [Github](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).
* For the automatic management and creation of the changelog especially at each release, we can use [git-cliff](https://github.com/orhun/git-cliff) which besides being written in Rust, is really handy.
* For the autobump versioning and `publish` workflow, I have some GHA that works really well.
I can work on It if you want.

**Comment by luizirber** [comment]
hey @Ebedthan, sorry for the delay!

> Concerning adding a template for issues, we can right away go with the template offered by [Github](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

Agree
 
> For the automatic management and creation of the changelog especially at each release, we can use [git-cliff](https://github.com/orhun/git-cliff) which besides being written in Rust, is really handy.

I've been maintaining the CHANGELOG manually, but this looks great!

> For the autobump versioning and `publish` workflow, I have some GHA that works really well.

Is it similar to the setup adopted in rust-bio? (just curious, but it seems to be working well there)

> I can work on It if you want.

That would be awesome!

**Comment by Ebedthan** [comment]
Hi @luizirber ,
Great! For the autobump versioning and publishing workflow, the one I [use](https://github.com/Ebedthan/sabreur/tree/main/.github/workflows) is slightly different from the one used by rust-bio but they are almost the same. I can work on this right away if you give me access to the repository.

**Comment by Ebedthan** [comment]
Hi @luizirber,

> Add GitHub templates for issues and PRs (examples)

PR #47 should resolve this.

**Comment by Ebedthan** [comment]
Hi @natir, @luizirber,

> add a publish workflow that send new crate version to crates.io ([example from sourmash](https://github.com/dib-lab/sourmash/blob/master/.github/workflows/rust_publish.yml))

I've added a continuous deployment to [my fork](https://github.com/Ebedthan/niffler/blob/master/.github/workflows/cd.yml) of niffler to solve the above comment. It needs a CRATES_IO_TOKEN to correctly work and is triggered on version tag creation. 

If you are good with it I will push a PR.

Anicet.

**Comment by natir** [comment]
@Ebedthan please do PR
