### ISSUE TITLE
Add XZ as a compression format alias for LZMA

### ISSUE THREAD

**Issue by dralley** [luizirber/niffler#39]
The whole network of compression algorithms and libraries is very confusing.  It would be helpful if users could specify ```Xz``` as a format rather than assuming they know about the distinction between XZ and LZMA.

https://github.com/luizirber/niffler/blob/master/src/basic/compression.rs#L117-L128

**Comment by natir** [comment]
Good point did you think PR #40 solve the trouble ?

**Comment by natir** [comment]
Solve by #40
