### ISSUE TITLE
bump MRV to 1.42

### ISSUE THREAD

**Issue by natir** [luizirber/niffler#41]
One of our dependency [object](https://crates.io/crates/object) us subslice pattern I think it's okay to change our MRV to 1.42.

If we did it we can also use this feature in our code, it should simplify [bytes2type](https://github.com/luizirber/niffler/blob/a49b0d5e45a54804636f60b264364dcb6ca4836d/src/basic/compression.rs#L39).

**Comment by natir** [comment]
@luizirber did you have an opinion on this ?

**Comment by luizirber** [comment]
I try to be conservative on the MSRV bumps, but if it is beneficial go for it!

**Comment by luizirber** [comment]
Fixed in #42
