### ISSUE TITLE
miniz_oxide is slow, provide some options to use different flate2 backends

### ISSUE THREAD

**Issue by dralley** [luizirber/niffler#53]
After looking at some flamegraphs and seeing that miniz_oxide was the majority of my program's runtime, I started enabling different flate2 backends to see if it would make a difference.  It did - the "cloudflare_zlib" backend was nearly 30% faster, and the system "zlib" backend around 15% faster.

If it was a pure IO benchmark (as opposed to all the XML parsing my application is doing) I expect it would be even more significant.

flate2 also has a simd feature that might be useful to expose, but I haven't tested it.

**Comment by dralley** [comment]
On a different system, the difference between miniz_oxide and cloudflare_zlib was closer to half of the runtime of the whole program.  As in it is twice as fast with the cloudflare_zlib backend.

**Comment by natir** [comment]
Ok realy nice thank for this benchmark.

We must found a way to let user of niffler acces to backend features, it's seems very important.
