### ISSUE TITLE
Concatenated bz2 causes silent data loss on read

### ISSUE THREAD

**Issue by Benjamin-Lee** [luizirber/niffler#61]
**Describe the bug**

I'm dealing with some concatenated bz2 files. Reading using niffler only reads the first file.

**Expected behavior**

Let's say you have two FASTA files, hello.fasta and world.fasta. If you compress both to produce hello.fasta.bz2 and world.fasta.bz2 and concatenate the two bz2 files, reading _that_ file using niffler will not read out any of the contents of world.fasta. If you were to concatenate hello.fasta and world.fasta _before_ compressing, it would then work as expected.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux] MacOS
 - OS version: [e.g. 20.04] 13.0
 - Rust version: [e.g. 1.54.0] 1.62.0
 - Niffler version: [e.g. 2.3.2] 2.4.0

**Comment by luizirber** [comment]
Good catch! I tried it out with `bzip2` and `bzcat` in the command line and got all info back from a concatenated bz2 file. 

The fix might be as simple as using [`MultiBzDecoder`](https://docs.rs/bzip2/0.4.4/bzip2/#multistreams-eg-wikipedia-or-pbzip2) in https://github.com/luizirber/niffler/blob/a29c1ef724396c9ba9c6ab76c8265aa0a588b8fe/src/basic/compression.rs#L82 , which would match what we do for gzip in https://github.com/luizirber/niffler/blob/a29c1ef724396c9ba9c6ab76c8265aa0a588b8fe/src/basic/compression.rs#L54
