### ISSUE TITLE
Allow user to choose compression level

### ISSUE THREAD

**Issue by natir** [luizirber/niffler#7]
We didn't allow the user to choose the compression level, the highest level is hardcode.

We can change the signature of `get_writer` in  `get_writer(out_stream: Box<dyn io::Write>, format: CompressionFormat, level: CompressionLevel)`.

So we need to create a struct `CompressionLevel` than can be converted in flate2 bzip2 and xz2 compression level. But I see in documentation [flate2](https://docs.rs/flate2/1.0.13/flate2/struct.Compression.html) and [xz2](https://docs.rs/xz2/0.1.6/xz2/bufread/struct.XzEncoder.html) allow 0-9 compression level (0 is no compression), bzip2 allow [fastest, best, default](https://docs.rs/bzip2/0.3.3/bzip2/enum.Compression.html).

A possible solution is in niffler we have 1 to 9 compression level (for me 0 have no sens) and convert directly in flate2 xz2 compression level type. For bzip2 1 -> fastest, 9 -> best, all other default.

Does someone have any alternative suggestions?

**Comment by luizirber** [comment]
closed in #10
